### ISSUE TITLE
some issues 

### ISSUE THREAD

**Issue by JoeSGT** [NipoCN/TabModifier#1]
Hello, 

i had ran into issues in regard of this plugin well first off let me list of versions that i was using
```
SpongeForge 1.12.2-2611-7.1.0-BETA-2944
TabModifer  1.0.0-SNAPSHOT
Luckperms 4.1.9
```

okay well few of my group in luckperms i use + and it seem you cannot use it with this plugin
if i use `vip+` the error is pretty much telling me it's unreadable, fact is if you use group with + the plugin breaks with a null error

and another thing how do you unset suffix from the config, because i don't use suffix only prefix here what i have try to do
```   
suffix=" "
 suffix=""
```
even tried taking out `suffix=""` of the config but it gave me a null ingame tab, and i ran a test server with 2 group default and vip it's not updating the prefix/suffix to the vip users

**Comment by NipoCN** [comment]
OK, I will check out what's wrong with it and I'll add features to disable prefix and suffix in next update

**Comment by NipoCN** [comment]
I've fixed this bug in the newest release, now support special characters like "+" in group name

**Comment by JoeSGT** [comment]
Ah it works i can use `+` it gave me an error at first it's because i need to set it like this
```
"vip+" {
    prefix="[vip+]"
    suffix="&9[default]"
}
```
add double quotes when using `+` Just wanted to say it here in case someone has this issue but thanks you for fixing it and adding a new features love the plugin <3
