### ISSUE TITLE
Header and Footer?

### ISSUE THREAD

**Issue by Spontini** [NipoCN/TabModifier#2]
Hello, is there a way to add header and footer? Also i installed the plugin, i've luckperms too but it doesnt show anything in tablist.

**Comment by NipoCN** [comment]
Sorry, this plugin is currently buggy and not working properly, I will try to fix it soon, you can use [tabmanager](https://forums.spongepowered.org/t/tab-manager-api-5-6-v-1-0-4-customize-your-tab-list/18351) instead, it works fine on API 7

**Comment by Spontini** [comment]
Okay mate, i've suggestion for you, try to add "online number, ping" features to header, footer it could be really nice!

**Comment by NipoCN** [comment]
New Version Released, I added simple Header & Footer features to tablist, I'll add placeholders to Header & Footer in next update, thanks for your suggestions

**Comment by Spontini** [comment]
Great, thanks
