### ISSUE TITLE
TabModifier seem to have broke randomly

### ISSUE THREAD

**Issue by JoeSGT** [NipoCN/TabModifier#3]
SpongeForge: 1.12.2-2611-7.1.0-BETA-2953
LuckPerms: 4.1.16
TabModifier: 1.2.0-SNAPSHOT.jar
here is how my config looks like
Config: https://pastebin.com/xqzwbpAX
Error: https://pastebin.com/8quvYE3a

**Comment by NipoCN** [comment]
You can ONLY set prefix through luckperms, my plugin itself does not handle prefix, DEFAUTL prefix only be useful when a group or user's prefix not set yet
I will fix this error and do some performance improvement in next update, thanks for your feedback..

**Comment by NipoCN** [comment]
Newer Version released, I fixed this problem simply abandon task event, I may not fully understand how this works

**Comment by JoeSGT** [comment]
thanks you
